name: bab
description: BeAndBrew.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+24

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  another_flushbar: ^1.12.30
  app_settings: ^5.1.1
  audioplayers: ^5.2.0
  badges: ^3.1.1
  carousel_slider: ^4.2.1
  chat_gpt_sdk: ^3.0.3
  circular_countdown_timer: ^0.2.3
  cloud_firestore: ^4.15.6
  cloud_functions: ^4.6.6
  code_text_field: ^1.1.0
  device_info_plus: ^9.0.2
  devicelocale: ^0.7.0
  dropdown_search: ^5.0.6
  email_validator: ^2.1.17
  expandable_text: ^2.3.0
  extended_image: ^8.2.0
  file_picker: ^6.1.1
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  firebase_messaging: ^14.7.17
  firebase_storage: ^11.6.7
  flex_color_picker: ^3.2.2
  flutter_blue_plus: ^1.31.14
  flutter_colorpicker: ^1.0.3
  flutter_dotenv: ^5.1.0
  flutter_easyloading: ^3.0.5
  flutter_highlight: ^0.7.0
  flutter_local_notifications: ^16.1.0
  flutter_markdown: ^0.6.20+1
  flutter_timezone: ^1.0.8
  flutter_rating_bar: ^4.0.1
  flutter_typeahead: ^5.2.0
  g_recaptcha_v3: ^0.0.5
  google_sign_in: ^6.2.1
  googleapis_auth: ^1.5.0
  i18n_extension: ^11.0.11
  image: ^4.0.17
  image_painter: ^0.6.1
  image_picker: ^1.0.7
  intl: ^0.18.1
  json_dynamic_widget: ^6.1.4
  logger: ^2.0.2+1
  markdown_editable_textinput: ^2.1.0
  package_info_plus: ^5.0.1
  palette_generator: ^0.3.3+2
  parallax_animation: ^0.0.3
  permission_handler: ^11.3.0
  phosphor_flutter: ^2.0.0
  provider: ^6.1.2
  shared_preferences: ^2.1.2
  shimmer: ^3.0.0
  sidebarx: ^0.16.1
  stack_board: ^0.1.2
  syncfusion_flutter_core: ^24.2.8
  syncfusion_flutter_datagrid: ^24.2.8
  syncfusion_flutter_gauges: ^24.2.8
  syncfusion_flutter_sliders: ^24.2.8
  table_calendar: ^3.0.9
  url_launcher: ^6.2.5
  uuid: ^4.1.0
  workmanager: ^0.5.2
  xml: ^6.5.0
#  dropdown_search: ^5.0.3
#  flutter_painter: ^1.0.1
#  syncfusion_flutter_calendar: ^21.1.39

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/.env
    - assets/data/
    - assets/html/
    - assets/images/
    - assets/locales/
    - assets/sounds/
    - assets/terms/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
    - family: BebasNeuePro
      fonts:
        - asset: fonts/BebasNeuePro-Regular.ttf
        - asset: fonts/BebasNeuePro-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
