// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAEsXWUis1p3rQSh7K7Xi6Rh2vD9utcXA',
    appId: '1:955480665092:web:b9943e1fe865871b59d951',
    messagingSenderId: '955480665092',
    projectId: 'brasseur-bordelais',
    authDomain: 'brasseur-bordelais.firebaseapp.com',
    databaseURL: 'https://brasseur-bordelais-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'brasseur-bordelais.appspot.com',
    measurementId: 'G-JDKVC86LYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJWa2a4Ge5DDfD2oIqdRecHF7q1fJAFd0',
    appId: '1:955480665092:android:e3b7bd21ccd6fa5759d951',
    messagingSenderId: '955480665092',
    projectId: 'brasseur-bordelais',
    databaseURL: 'https://brasseur-bordelais-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'brasseur-bordelais.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiQtMKGzSYK9cBXrHcLdZNhrSX2pbkcHE',
    appId: '1:955480665092:ios:9f036ad4bda4b58959d951',
    messagingSenderId: '955480665092',
    projectId: 'brasseur-bordelais',
    databaseURL: 'https://brasseur-bordelais-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'brasseur-bordelais.appspot.com',
    iosClientId: '955480665092-tvire7q52i740rsng3mq7cfnmscom5cc.apps.googleusercontent.com',
    iosBundleId: 'com.fixiply.bb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiQtMKGzSYK9cBXrHcLdZNhrSX2pbkcHE',
    appId: '1:955480665092:ios:9f036ad4bda4b58959d951',
    messagingSenderId: '955480665092',
    projectId: 'brasseur-bordelais',
    databaseURL: 'https://brasseur-bordelais-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'brasseur-bordelais.appspot.com',
    iosClientId: '955480665092-tvire7q52i740rsng3mq7cfnmscom5cc.apps.googleusercontent.com',
    iosBundleId: 'com.fixiply.bb',
  );
}
