// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0M2m4ywAyaBqEnyXvYBdSybSgtQBOGFM',
    appId: '1:94135687117:web:1eeccf8f5e36c7ccca1684',
    messagingSenderId: '94135687117',
    projectId: 'beandbrew',
    authDomain: 'beandbrew.firebaseapp.com',
    storageBucket: 'beandbrew.appspot.com',
    measurementId: 'G-46JRTNPPYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPEbLsKz6nNIAvRNtIFZzSehTFCntJ2qY',
    appId: '1:94135687117:android:60908768de2a724dca1684',
    messagingSenderId: '94135687117',
    projectId: 'beandbrew',
    storageBucket: 'beandbrew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKnxvQJWoCbEVKNjjiBA3uZmBLfn4Kng8',
    appId: '1:94135687117:ios:bf0935c8fb93be4eca1684',
    messagingSenderId: '94135687117',
    projectId: 'beandbrew',
    storageBucket: 'beandbrew.appspot.com',
    androidClientId: '94135687117-e3grq4jekda8r41qnohr21tt2ve31vna.apps.googleusercontent.com',
    iosClientId: '94135687117-pdhnsvd8n6ohe80d8dqr8d0ifv6i80o9.apps.googleusercontent.com',
    iosBundleId: 'com.fixiply.bab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKnxvQJWoCbEVKNjjiBA3uZmBLfn4Kng8',
    appId: '1:94135687117:ios:bf0935c8fb93be4eca1684',
    messagingSenderId: '94135687117',
    projectId: 'beandbrew',
    storageBucket: 'beandbrew.appspot.com',
    androidClientId: '94135687117-e3grq4jekda8r41qnohr21tt2ve31vna.apps.googleusercontent.com',
    iosClientId: '94135687117-pdhnsvd8n6ohe80d8dqr8d0ifv6i80o9.apps.googleusercontent.com',
    iosBundleId: 'com.fixiply.bab',
  );
}
